inputs:
  token:
    description: github token
    required: false
    default: ''

  arch:
    description: system platform
    required: false
    default: x64


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ inputs.token }}
        branch: upstream
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ inputs.arch }}


    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ inputs.arch }}



    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>"
          git merge origin/$1
          echo ""
        }

        # merge mingw-flags



    - shell: bash
      env:
        - CC: "ccache $MINGW_CC"
        - CXX: "ccache $MINGW_CXX"
      run: |
        make win32



    - uses: actions/upload-artifact@main
      with:
        name: flips-${{ inputs.arch }}
        path: ${{ github.workspace }}/*.exe
