inputs:
  token:
    description: github token
    required: false
    default: ''

  arch:
    description: system platform
    required: false
    default: x64


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ inputs.token }}
        branch: upstream
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ inputs.arch }}


    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ inputs.arch }}



    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>";
          if [[ -z "$2" ]]; then
            git merge origin/$1 || { git diff --diff-filter=U; exit 1; }
          else
            git merge origin/$1 || { git diff --diff-filter=U; git merge --abort; git merge -X $2 origin/$1; }
          fi
          echo "";
        }

        merge mingw-flags



    - shell: bash
      env:
        CC: "ccache ${{ env.MINGW_CC }}"
        CXX: "ccache ${{ env.MINGW_CXX }}"
        WINDRES: "${{ env.MINGW_WINDRES }}"
      run: |
        make



    - uses: actions/upload-artifact@main
      with:
        name: flips-${{ inputs.arch }}
        path: ${{ github.workspace }}/*.exe
