on:
  workflow_dispatch:
  schedule:
    - cron: '45 3 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/fl1ps@cron
        with:
          token: ${{ secrets.token }}
